services:
  # Frontend приложение
  gim-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://services.simurg.space/gim-tec-forecast
      - NEXT_PUBLIC_API_BASE_URL=https://services.simurg.space/gim-tec-forecast
    restart: unless-stopped
    networks:
      - gim-network

  # Раскомментируйте если нужно запускать backend локально
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8088:8088"
  #   restart: unless-stopped

networks:
  gim-network:
    driver: bridge

# Для разработки можно добавить volume для hot-reload
# volumes:
#   node_modules: 