version: '3.8'

services:
  # Frontend приложение
  gim-frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://services.simurg.space/gim-tec-forecast
      - NEXT_PUBLIC_API_BASE_URL=https://services.simurg.space/gim-tec-forecast
    restart: unless-stopped
    networks:
      - gim-network
    # Healthcheck для проверки доступности сервиса
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Конфигурация для разработки
  gim-frontend-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    profiles: ["dev"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8088}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8088}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - gim-network
    command: npm run dev

  # Раскомментируйте если нужно запускать backend локально
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8088:8088"
  #   restart: unless-stopped

networks:
  gim-network:
    driver: bridge

# Для разработки можно добавить volume для hot-reload
# volumes:
#   node_modules: 