FROM node:18-alpine

WORKDIR /app

# Установка зависимостей для Alpine Linux
RUN apk add --no-cache libc6-compat

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Отключаем телеметрию Next.js
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV development

# Порт для Next.js
EXPOSE 3000

# Команда при запуске контейнера
CMD ["npm", "run", "dev"] 